import { describe, expect, it } from 'vitest'

import candidate from '../../supabase/candidates/20260823013000_capacity_funded_individual_review_calendar.sql?raw'

describe('capacity-funded individualized REVIEW calendar candidate', () => {
  it('covers exactly 38 dates and derives a personal 1..8 daily load from remaining capacity', () => {
    expect(candidate).toContain("date '2026-08-23'")
    expect(candidate).toContain("date '2026-09-29'")
    expect(candidate).toContain('date_count')
    expect(candidate).toContain('fresh_questions < 38')
    expect(candidate).toContain('least(coalesce(sum(capacity.initial_questions), 0)::integer, 38 * 8)')
    expect(candidate).toContain('student.scheduled_questions / dates.date_count')
    expect(candidate).toContain('mod(student.scheduled_questions, dates.date_count)')
    expect(candidate).toContain('question_count not between 1 and 8')
    expect(candidate).not.toMatch(/question_count\s*=\s*5/i)
  })

  it('uses only active approved in-scope source originals and excludes all four used identities', () => {
    expect(candidate).toContain("release.status = 'active'")
    expect(candidate).toContain("release.verification_status = 'full_visual_verified'")
    expect(candidate).toContain("question.review_status = 'approved'")
    expect(candidate).toContain("question.scope_status = 'IN'")
    expect(candidate).toContain('question.usable_for_review')
    expect(candidate).toContain("question.source_kind = 'licensed_local'")
    expect(candidate).toContain("question.render_mode = 'image_primary'")
    expect(candidate).toContain("asset->>'kind' = 'question_image'")
    expect(candidate).toContain("asset->>'kind' = 'analysis_image'")
    expect(candidate).toContain('used.question_id = question.id')
    expect(candidate).toContain('used.mother_id = question.mother_id')
    expect(candidate).toContain('used.source_item_key = question.source_item_key')
    expect(candidate).toContain('used.content_fingerprint = question.content_fingerprint')
    expect(candidate).toContain("answer.question_snapshot->>'sourceItemKey'")
    expect(candidate).toContain("answer.question_snapshot->>'contentFingerprint'")
  })

  it('budgets only selector-compatible difficulty visits and skips mastered dead ends', () => {
    expect(candidate).toContain('create temporary table _latest_concept_state')
    expect(candidate).toContain('latest.correct and not latest.uncertain')
    expect(candidate).toContain('question.level > latest.question_level')
    expect(candidate).toContain('(not latest.correct or latest.uncertain)')
    expect(candidate).toContain('question.level <= latest.question_level')
    expect(candidate).toContain('Concepts with no')
    expect(candidate).toContain('compatible next level are omitted')
  })

  it('uses the reviewed 130-row catalog and never treats a raw H3 key as a label', () => {
    expect(candidate).toContain('app_private.chem_review_concept_catalog')
    expect(candidate).toContain("count(*) from app_private.chem_review_concept_catalog) <> 130")
    expect(candidate).toContain("grade_band='高一') <> 35")
    expect(candidate).toContain("grade_band='高二') <> 40")
    expect(candidate).toContain("grade_band='高三') <> 55")
    expect(candidate).toContain('catalog.concept_label')
    expect(candidate).toContain("catalog.concept_label = catalog.concept_key")
    expect(candidate).not.toContain("question.source_info->>'conceptLabel'")
    expect(candidate).not.toContain("question.source_info->>'concept_name'")
  })

  it('reserves concept capacity before writing and keeps all three plan arrays parallel', () => {
    expect(candidate).toContain('create temporary table _remaining_capacity')
    expect(candidate).toContain('remaining_questions = capacity.remaining_questions - 1')
    expect(candidate).toContain('reserved_questions = capacity.reserved_questions + 1')
    expect(candidate).toContain('reserved_questions > capacity.initial_questions')
    expect(candidate).toContain('target_count.reserved > coalesce(fresh_count.questions, 0)')
    expect(candidate).toContain('target_count.reserved > coalesce(fresh_count.mothers, 0)')
    expect(candidate).toContain('target_count.reserved > coalesce(fresh_count.sources, 0)')
    expect(candidate).toContain('target_count.reserved > coalesce(fresh_count.fingerprints, 0)')
    expect(candidate).toContain('cardinality(assignment.skill_ids) not between 1 and assignment.question_count')
    expect(candidate).toContain('cardinality(assignment.target_concept_keys) <> assignment.question_count')
    expect(candidate).toContain('cardinality(assignment.knowledge_summaries) <> assignment.question_count')
    expect(candidate).toContain('unique (student_id, plan_date, concept_key)')
  })

  it('hard-covers every not-yet-answered first-pass concept before writing', () => {
    expect(candidate).toContain('First-pass is a hard curriculum contract')
    expect(candidate).toContain('create temporary table _required_first_pass')
    expect(candidate).toContain('real historical REVIEW answer')
    expect(candidate).toContain('Answer locks are deliberately')
    expect(candidate).toContain('from _latest_concept_state historical')
    expect(candidate).toContain("student.grade_band <> '高一'")
    expect(candidate).toContain('catalog.skill_id = any(student.confirmed_h1_skills)')
    expect(candidate).toContain('all H2=40 concepts')
    expect(candidate).toContain('all H3=55 concepts')
    expect(candidate).toContain('first-pass catalog concept has no compatible fresh original')
    expect(candidate).toContain('from _required_first_pass required')
    expect(candidate).toContain('when capacity.reserved_questions = 0')
    expect(candidate).toContain('first-pass concept coverage missing from the 38-day REVIEW targets')
    const coverageCheck = candidate.indexOf('first-pass concept coverage missing from the 38-day REVIEW targets')
    const firstPlanWrite = candidate.indexOf('insert into public.chem_learning_plans')
    expect(coverageCheck).toBeGreaterThan(-1)
    expect(coverageCheck).toBeLessThan(firstPlanWrite)
  })

  it('keeps every High-1 target in confirmed scope and personalizes the stable course rotation', () => {
    expect(candidate).toContain("student.metadata->'confirmedLearnedSkillIds'")
    expect(candidate).toContain("'H1_REACTION_CLASSIFICATION','H1_SOLUTION_CONCENTRATION'")
    expect(candidate).toContain('capacity.skill_id = any(v_student.confirmed_h1_skills)')
    expect(candidate).not.toContain("v_day.plan_date >= date '2026-09-01'")
    expect(candidate).toContain('hashtextextended(student.id::text, 0)')
    expect(candidate).toContain('v_student.date_rotation')
    expect(candidate).toContain('capacity.skill_order')
    expect(candidate).toContain('capacity.concept_order')
    expect(candidate).toContain('Jiangsu Selective Compulsory 1 course spine only')
    expect(candidate).toContain('High-3 error-prone/high-frequency exam spine first')
    expect(candidate).not.toContain('chem_student_skill_state')
  })

  it('creates missing 09-26..09-29 dates without touching learning evidence or quizzes', () => {
    expect(candidate).toContain('insert into public.chem_learning_plans')
    expect(candidate).toContain('update public.chem_learning_plans plan')
    expect(candidate).toContain("plan.mode = 'REVIEW'")
    expect(candidate).toContain('round_limit = 1')
    expect(candidate).toContain('the candidate window contains a started REVIEW plan')
    expect(candidate).not.toMatch(/(?:insert\s+into|update|delete\s+from)\s+public\.chem_learning_attempts/i)
    expect(candidate).not.toMatch(/(?:insert\s+into|update|delete\s+from)\s+public\.chem_attempt_answers/i)
    expect(candidate).not.toMatch(/(?:insert\s+into|update|delete\s+from)\s+public\.quiz_sessions/i)
  })

  it('treats answer locks as started and never reuses a locked source identity', () => {
    expect(candidate).toContain('lock table app_private.chem_question_answer_locks in share mode')
    expect(candidate).toContain('from app_private.chem_question_answer_locks answer_lock')
    expect(candidate).toContain('answer_lock.question_id')
    expect(candidate).toContain('question.mother_id')
    expect(candidate).toContain('question.source_item_key')
    expect(candidate).toContain('question.content_fingerprint')
    expect(candidate).toContain('answer-locked REVIEW plan')
  })

  it('stores unique plan skills by their first target position', () => {
    expect(candidate).toContain('min(owned.target_order) as first_target_order')
    expect(candidate).toContain('group by owned.skill_id')
    expect(candidate).toContain('order by skill.first_target_order, skill.skill_id')
  })

  it('documents that runtime wrong/uncertain replacement must re-budget the future suffix', () => {
    expect(candidate).toContain('chem_personalize_next_review_plan may replace')
    expect(candidate).toContain('re-budget the still-unstarted suffix')
    expect(candidate).toContain('CANDIDATE ONLY')
  })
})
